development:
  adapter: mysql
  encoding: utf8
  database: passthemonkey_development
  username: root
  password:
  
test:
  adapter: mysql
  encoding: utf8
  database: bort_test
  username: root
  password:
  
production:
  adapter: mysql
  encoding: utf8
  database: bort_production
  username: root
  password:
