development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Pass the Monkey
  admin_email: traviskroberts@gmail.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://passthemonkey.r09.railsrumble.com/
  site_name: Pass the Monkey
  admin_email: support@passthemonkey.com
